spring:
  application:
    name: back
  config:
    import: optional:file:.env[.properties] # .env 파일을 읽도록 하는 설정
  ai:
    openai:
      base-url: https://api.groq.com/openai/v1 # 이렇게 재정의를 해야 OPENAI API 대신 GROQ API를 사용할 수 있다.
      api-key: ${GROQ_API_KEY}
      chat:
        model: meta-llama/llama-4-scout-17b-16e-instruct # 라마 모델을 사용할 것이다.
        temperature: 0 # LLM의 창의성을 없애는 설정, 꼭 필요하다.
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always # 채팅 메세지 테이블이 없으면 무조건 생성하도록
            platform: mariadb # 채팅 메세지 테이블 스키마 파일 선택(mysql을 사용한다고 하더라도 mariadb 스키마 파일을 사용해야 한다.)
  datasource:
    url: jdbc:h2:./db_dev;MODE=MariaDB # 실제 MySQL(MariaDB)를 사용해도 되지만 개발환경이기 때문에 편하게 H2를 MariaDB 모드로 사용
    username: sa
    password:
    driver-class-name: org.h2.Driver
logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG